### ISSUE TITLE
Replace react-photo-gallery

### ISSUE THREAD

**Issue by igordanchenko** [sanity-io/sanity-plugin-asset-source-unsplash#9]
Hi @skogsmaskin,

I came across this repo while searching for active projects using `react-photo-gallery` library. `react-photo-gallery` hasn't been maintained for almost 3 years and still has a hard peer dependency on React 16. At this point, it's safe to assume its author abandoned the library for good. 

I'm the maintainer of [`react-photo-album`](https://github.com/igordanchenko/react-photo-album) library, a successor to `react-photo-gallery`. `react-photo-album` is very similar to the original library and requires just some minor tweaks to migrate. 

Please let me know if you are interested, and I'll be happy to assist with PR.

**Comment by skogsmaskin** [comment]
Hey @igordanchenko!

This is great, thank you for succeeding the library. We are very interested with your assistance.

**Comment by igordanchenko** [comment]
@skogsmaskin, the PR is ready.

**Comment by skogsmaskin** [comment]
@igordanchenko - sorry for the late reply due to covid. Thank you for this!

**Comment by skogsmaskin** [comment]
@igordanchenko - a dedicated team at our company has taken over the responsibility for our plugins and such (yes we have been growing a lot lately).  I have notified them to follow up on your PR!

**Comment by snorrees** [comment]
@igordanchenko - great work :) I've tested the changes and upgrade-path, it all looks good. Off to merging and releasing a new version. Thank you!
